org: s6007589
app: task-pdf-writer
service: aws-python-api

frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: "20201221"
  environment:
    DJANGO_SETTINGS_MODULE: settings

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
  render:
    handler: handler.render
    events:
      - http:
          path: /render
          method: post

plugins:
  - serverless-offline
  - serverless-python-requirements
