org: s6007589
app: task-pdf-writer
service: aws-node-api

frameworkVersion: "2"

custom:
  tableName: "users-table-${self:provider.stage}"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  stage: dev
  region: ap-southeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
  environment:
    USERS_TABLE: ${self:custom.tableName}

layers:
  wkhtmltoxLayer:
    name: wkhtmltox
    description: wkhtmltox binaries for pdf/image generation
    package:
      artifact: wkhtmltox-0.12.6-4.amazonlinux2_lambda.zip

functions:
  pdf:
    handler: handler-pdf.handler
    layers:
      - { Ref: WkhtmltoxLayerLambdaLayer }
    environment:
      FONTCONFIG_PATH: /opt/fonts
    events:
      - http:
          path: pdf/
          method: ANY
      - http:
          path: pdf/{proxy+}
          method: ANY
  api:
    handler: handler.handler
    events:
      - http:
          path: api/
          method: ANY
      - http:
          path: api/{proxy+}
          method: ANY

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
